=== michaelsogos/primebrick-sdk/src/schemas/base-view-definition.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://primebrick-sdk/base-view-definition.schema.json",
    "title": "BaseViewDefinition",
    "description": "The base view definition model",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "JSON Schema URL or path",
            "type": "string"
        },
        "type": {
            "description": "View type",
            "type": "string",
            "enum": ["grid", "form", "cards"]
        },
        "version": {
            "description": "Definition version",
            "type": "string"
        },
        "name": {
            "description": "View name",
            "type": "string"
        },
        "labelKey": {
            "description": "View title translatable key",
            "type": "string"
        },
        "icon": {
            "description": "View icon",
            "type": "string"
        },
        "color": {
            "description": "View main color",
            "type": "string"
        },
        "brick": {
            "description": "Brick name",
            "type": "string"
        },
        "entity": {
            "description": "Entity definition",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Entity name to query",
                    "type": "string"
                },
                "labelKey": {
                    "description": "Entity translation key",
                    "type": "string"
                },
                "recordNameTemplate": {
                    "description": "Template literal to build record name using ES6 syntax",
                    "examples": [
                        "for User entity it could be '${first_name} ${last_name} (${code})' => 'Michael Sogos (USR001)'",
                        "for Sale Order it could be '${code} - ${total_amount - total_discount}€' => 'ORD001 - 123.00€'"
                    ],
                    "type": "string"
                }
            },
            "required": ["name", "labelKey", "recordNameTemplate"],
            "additionalProperties": false
        },
        "showLogs": {
            "description": "True to show logs on footer",
            "type": "boolean",
            "default": false
        },
        "definition": {
            "description": "View definition",
            "type": "object"
        }
    },
    "required": ["name", "labelKey", "definition", "brick", "entity", "type", "version"],
    "additionalProperties": false,
    "allOf": [
        {
            "if": {
                "properties": {
                    "type": {
                        "const": "grid"
                    }
                }
            },
            "then": {
                "properties": {
                    "definition": {
                        "$ref": "grid-view-definition.schema.json#"
                    }
                }
            }
        },
        {
            "if": {
                "properties": {
                    "type": {
                        "const": "form"
                    }
                }
            },
            "then": {
                "properties": {
                    "definition": {
                        "$ref": "form-view-definition.schema.json#"
                    }
                }
            }
        },
        {
            "if": {
                "properties": {
                    "type": {
                        "const": "cards"
                    }
                }
            },
            "then": {
                "properties": {
                    "definition": {
                        "$ref": "cards-view-definition.schema.json#"
                    }
                }
            }
        }
    ]
}

=== michaelsogos/primebrick-sdk/src/schemas/card-view-test.json
{
    "$schema": "./base-view-definition.schema.json",
    "type": "cards",
    "name": "translations-grid",
    "labelKey": "translations",
    "brick": "core",
    "showLogs": true,
    "version": "1.0.0",
    "entity": {
        "name": "MetaTranslation",
        "labelKey": "translation",
        "recordNameTemplate": "Key: ${key}, Lang: ${languageCode}, Group: ${group}"
    },
    "definition": {
        "fields": [
            {
                "name": "key",
                "labelKey": "key",
                "layout": {
                    "isTitle": true
                }
            },
            {
                "name": "languageCode",
                "labelKey": "language-code",
                "layout": {
                    "line": 1,
                    "filling": ["left"]
                }
            },
            {
                "name": "value",
                "labelKey": "translation",
                "layout": {
                    "line": 2,
                    "filling": ["left", "middle", "right"],
                    "hideLabel": true,
                    "isBold": true,
                    "isDetail": true
                }
            },
            {
                "name": "group",
                "labelKey": "group",
                "layout": {
                    "line": 1,
                    "filling": ["middle"],
                    "align": "center",
                    "isChip": true
                }
            },
            {
                "name": "isTemplate",
                "labelKey": "template",
                "type": "boolean",
                "layout": {
                    "line": 1,
                    "filling": ["right"],
                    "align": "right"
                }
            },
            {
                "name": "deletedOn",
                "isArchiveFlag": true,
                "disableSort": true
            }
        ],
        "sorts": [
            {
                "field": "key"
            }
        ],
        "alternativeViews": [
            {
                "name": "translations-grid",
                "type": "grid"
            }
        ],
        "highlighters": [
            {
                "expression": "group == 'login'",
                "border": {
                    "color": "teal lighten-4",
                    "sides": ["left"]
                },
                "title": {
                    "color": "teal"
                },
                "icon": {
                    "color": "teal",
                    "name": "mdi-card-text"
                }
            },
            {
                "expression": "deletedOn",
                "border": {
                    "color": "error lighten-4",
                    "sides": ["left"]
                },
                "title": {
                    "color": "error"
                }
            }
        ],
        "options": {
            "enableRecordNameAsSubTitle": true
        },
        "actions": {
            "open": {
                "view": "translations-form",
                "enableDoubleClick": false,
                "enableItemButton": true
            },
            "edit": {
                "view": "translations-form",
                "enableDoubleClick": true,
                "enableItemButton": true
            },
            "add": {
                "view": "translations-form",
                "enableToolbarButton": true,
                "enableFloatingButton": true,
                "enableMenuLink": true
            },
            "delete": {
                "enableToolbarButton": true,
                "enableItemButton": true,
                "enableMenuLink": true
            },
            "archive": {
                "enableToolbarButton": true,
                "enableItemButton": true,
                "enableMenuLink": true
            },
            "restore": {
                "enableToolbarButton": true,
                "enableItemButton": true,
                "enableMenuLink": true
            },
            "refresh": {
                "enableToolbarButton": true,
                "enableMenuLink": true
            },
            "archivedFilter": {
                "enableToolbarButton": true
            },
            "search": {
                "enableToolbarButton": true,
                "fields": ["key", "value"]
            },
            "filter": {
                "enableHeader": true,
                "enableDialog": true,
                "fields": [
                    {
                        "field": "key",
                        "type": "string"
                    },
                    {
                        "field": "languageCode",
                        "type": "list",
                        "listOptions": {
                            "enableMultiSelection": true,
                            "values": [
                                {
                                    "labelKey": "italian",
                                    "value": "it"
                                },
                                {
                                    "labelKey": "english",
                                    "value": "en"
                                },
                                {
                                    "labelKey": "french",
                                    "value": "fr"
                                },
                                {
                                    "labelKey": "spanish",
                                    "value": "es"
                                }
                            ]
                        }
                    },
                    {
                        "field": "group",
                        "type": "list",
                        "listOptions": {
                            "enableMultiSelection": true,
                            "query": {
                                "brick": "core",
                                "entity": "MetaTranslationGroup",
                                "valueFieldName": "group",
                                "textFieldName": "group",
                                "searchFields": ["group"],
                                "sorts": [
                                    {
                                        "field": "group",
                                        "direction": "DESC"
                                    }
                                ]
                            }
                        }
                    }
                ]
            }
        },
        "aggregators": [
            {
                "expression": "COUNT($self.id)",
                "labelKey": "all"
            },
            {
                "expression": "COUNT($self.id)",
                "labelKey": "template",
                "color": "success",
                "filters": [
                    {
                        "expressions": ["$self.isTemplate = :istemplate"],
                        "expressionValues": { "istemplate": true }
                    }
                ]
            }
        ]
    }
}

=== michaelsogos/primebrick-sdk/src/schemas/form-view-test.json
{
    "$schema": "./base-view-definition.schema.json",
    "name": "translations-form",
    "labelKey": "translation",
    "brick": "core",
    "entity": {
        "name": "MetaTranslation",
        "labelKey": "translation",
        "recordNameTemplate": "Key: ${key}, Lang: ${languageCode}, Group: ${group}"
    },
    "type": "form",
    "version": "1.0.0",
    "showLogs": true,
    "definition": {
        "containers": [
            {
                "cols": 9,
                "showTitle": false,
                "fields": [
                    {
                        "name": "key",
                        "labelKey": "key",
                        "cols": 6,
                        "type": "textbox",
                        "validationRules": [
                            {
                                "rule": "required",
                                "labelKey": "field_required"
                            }
                        ],
                        "translatable": false
                    },
                    {
                        "name": "languageCode",
                        "labelKey": "language-code",
                        "cols": 6,
                        "validationRules": [
                            {
                                "rule": "required",
                                "labelKey": "field_required"
                            }
                        ]
                    },
                    {
                        "name": "value",
                        "labelKey": "translation"
                    },
                    {
                        "name": "group",
                        "labelKey": "group"
                    },
                    {
                        "name": "isTemplate",
                        "labelKey": "template",
                        "validationRules": [
                            {
                                "rule": "required",
                                "labelKey": "field_required"
                            }
                        ],
                        "type": "checkbox"
                    }
                ]
            },
            {
                "cols": 3,
                "showTitle": false,
                "fields": [
                    {
                        "name": "key",
                        "labelKey": "key",
                        "cols": 6,
                        "type": "textbox",
                        "validationRules": [
                            {
                                "rule": "required",
                                "labelKey": "field_required"
                            }
                        ],
                        "translatable": false
                    },
                    {
                        "name": "languageCode",
                        "labelKey": "language-code",
                        "cols": 6
                    },
                    {
                        "name": "value",
                        "labelKey": "translation"
                    },
                    {
                        "name": "group",
                        "labelKey": "group"
                    },
                    {
                        "name": "isTemplate",
                        "labelKey": "template",
                        "validationRules": [
                            {
                                "rule": "required",
                                "labelKey": "field_required"
                            }
                        ],
                        "type": "switch"
                    }
                ]
            },
            {
                "cols": 3,
                "showTitle": false,
                "fields": [
                    {
                        "name": "key",
                        "labelKey": "key",
                        "cols": 6,
                        "type": "textbox",
                        "validationRules": [
                            {
                                "rule": "required",
                                "labelKey": "validation-message-field-is-required"
                            }
                        ],
                        "translatable": false
                    },
                    {
                        "name": "languageCode",
                        "labelKey": "language-code",
                        "cols": 6
                    },
                    {
                        "name": "value",
                        "labelKey": "translation"
                    },
                    {
                        "name": "group",
                        "labelKey": "group"
                    },
                    {
                        "name": "isTemplate",
                        "labelKey": "template",
                        "type": "checkbox"
                    }
                ]
            },
            {
                "cols": 9,
                "showTitle": false,
                "fields": [
                    {
                        "name": "key",
                        "labelKey": "key",
                        "cols": 6,
                        "type": "textbox",
                        "validationRules": [
                            {
                                "labelKey": "validation-message-field-is-required",
                                "rule": "required"
                            }
                        ],
                        "translatable": false
                    },
                    {
                        "name": "languageCode",
                        "labelKey": "language-code",
                        "cols": 6
                    },
                    {
                        "name": "value",
                        "labelKey": "translation"
                    },
                    {
                        "name": "group",
                        "labelKey": "group"
                    },
                    {
                        "name": "isTemplate",
                        "labelKey": "template",
                        "type": "textbox"
                    }
                ]
            }
        ],
        "actions": {
            "save": {
                "enableToolbarButton": true,
                "enableMenuLink": true
            },
            "delete": {
                "enableToolbarButton": false,
                "enableMenuLink": false
            },
            "archive": {
                "enableToolbarButton": false,
                "enableMenuLink": false
            },
            "refresh": {
                "enableToolbarButton": false,
                "enableMenuLink": false
            },
            "info": {
                "enableToolbarButton": false,
                "enableMenuLink": true
            }
        }
    }
}
